networks:
  kafka_network:
    driver: bridge
  redis_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.38.0.0/16
          gateway: 172.38.0.1

services:
  redis-1:
    image: redis
    container_name: redis-1
    command: [ "redis-server","/usr/local/etc/redis/redis.conf" ]
    volumes:
      - redis1:/data
      - ./redis/node-1/conf/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6371:6379
      - 16371:16379
    networks:
      redis_network:
        ipv4_address: 172.38.0.11
  redis-2:
    image: redis
    container_name: redis-2
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    volumes:
      - redis2:/data
      - ./redis/node-2/conf/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6372:6379"
      - 16372:16379
    networks:
      redis_network:
        ipv4_address: 172.38.0.12

  redis-3:
    image: redis
    container_name: redis-3
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    volumes:
      - redis3:/data
      - ./redis/node-3/conf/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6373:6379"
      - 16373:16379
    networks:
      redis_network:
        ipv4_address: 172.38.0.13

  redis-4:
    image: redis
    container_name: redis-4
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    volumes:
      - redis4:/data
      - ./redis/node-4/conf/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6374:6379"
      - 16374:16379
    networks:
      redis_network:
        ipv4_address: 172.38.0.14

  redis-5:
    image: redis
    container_name: redis-5
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    volumes:
      - redis5:/data
      - ./redis/node-5/conf/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6375:6379"
      - 16375:16379
    networks:
      redis_network:
        ipv4_address: 172.38.0.15

  redis-6:
    image: redis
    container_name: redis-6
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    volumes:
      - redis6:/data
      - ./redis/node-6/conf/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6376:6379"
      - "16376:16379"
    networks:
      redis_network:
        ipv4_address: 172.38.0.16

  redis-insight:
    image: redislabs/redisinsight:latest
    container_name: redis-insight
    ports:
      - "5540:5540"
    volumes:
      - redisinsight:/db
    depends_on:
      - redis-1
      - redis-2
      - redis-3
      - redis-4
      - redis-5
      - redis-6
    networks:
      - redis_network

  zookeeper:
    image: bitnami/zookeeper:3.9.1
    container_name: zookeeper
    tmpfs: "/zktmp"
    environment:
      ALLOW_ANONYMOUS_LOGIN: 'yes'
    ports:
      - "2181:2181"
    networks:
      - kafka_network

  kafka1:
    image: bitnami/kafka:3.7.0
    container_name: kafka1
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,EXTERNAL://0.0.0.0:29092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092,EXTERNAL://localhost:29092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: 'true'
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_CFG_NUM_PARTITIONS: 3
    ports:
      - "9092:9092"
      - "29092:29092"
    volumes:
      - kafka_data_1:/bitnami/kafka
    networks:
      - kafka_network

  kafka2:
    image: bitnami/kafka:3.7.0
    container_name: kafka2
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9093,EXTERNAL://0.0.0.0:29093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9093,EXTERNAL://localhost:29093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: 'true'
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_CFG_NUM_PARTITIONS: 3
    ports:
      - "9093:9093"
      - "29093:29093"
    volumes:
      - kafka_data_2:/bitnami/kafka
    networks:
      - kafka_network

  kafka3:
    image: bitnami/kafka:3.7.0
    container_name: kafka3
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9094,EXTERNAL://0.0.0.0:29094
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:9094,EXTERNAL://localhost:29094
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: 'true'
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_CFG_NUM_PARTITIONS: 3
    ports:
      - "9094:9094"
      - "29094:29094"
    volumes:
      - kafka_data_3:/bitnami/kafka
    networks:
      - kafka_network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    ports:
      - "8085:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka1:9092,kafka2:9093,kafka3:9094
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    networks:
      - kafka_network

volumes:
  redisinsight:
    name: redisinsight
  redis1:
    name: redis1
  redis2:
    name: redis2
  redis3:
    name: redis3
  redis4:
    name: redis4
  redis5:
    name: redis5
  redis6:
    name: redis6
  kafka_data_1:
    name: kafka_data_1
    driver: local
  kafka_data_2:
    name: kafka_data_2
    driver: local
  kafka_data_3:
    name: kafka_data_3
    driver: local