networks:
  redis_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.38.0.0/16
          gateway: 172.38.0.1

services:
  redis-1:
    image: redis
    container_name: redis-1
    command: [ "redis-server","/usr/local/etc/redis/redis.conf" ]
    volumes:
      - redis1:/data
      - ./redis/node-1/conf/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6371:6379
      - 16371:16379
    networks:
      redis_network:
        ipv4_address: 172.38.0.11
  redis-2:
    image: redis
    container_name: redis-2
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    volumes:
      - redis2:/data
      - ./redis/node-2/conf/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6372:6379"
      - 16372:16379
    networks:
      redis_network:
        ipv4_address: 172.38.0.12

  redis-3:
    image: redis
    container_name: redis-3
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    volumes:
      - redis3:/data
      - ./redis/node-3/conf/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6373:6379"
      - 16373:16379
    networks:
      redis_network:
        ipv4_address: 172.38.0.13

  redis-4:
    image: redis
    container_name: redis-4
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    volumes:
      - redis4:/data
      - ./redis/node-4/conf/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6374:6379"
      - 16374:16379
    networks:
      redis_network:
        ipv4_address: 172.38.0.14

  redis-5:
    image: redis
    container_name: redis-5
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    volumes:
      - redis5:/data
      - ./redis/node-5/conf/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6375:6379"
      - 16375:16379
    networks:
      redis_network:
        ipv4_address: 172.38.0.15

  redis-6:
    image: redis
    container_name: redis-6
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    volumes:
      - redis6:/data
      - ./redis/node-6/conf/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6376:6379"
      - "16376:16379"
    networks:
      redis_network:
        ipv4_address: 172.38.0.16

  redis-insight:
    image: redislabs/redisinsight:latest
    container_name: redis-insight
    ports:
      - "5540:5540"
    volumes:
      - redisinsight:/db
    depends_on:
      - redis-1
      - redis-2
      - redis-3
      - redis-4
      - redis-5
      - redis-6
    networks:
      - redis_network

volumes:
  redisinsight:
    name: redisinsight
  redis1:
    name: redis1
  redis2:
    name: redis2
  redis3:
    name: redis3
  redis4:
    name: redis4
  redis5:
    name: redis5
  redis6:
    name: redis6